### ISSUE TITLE
Youtube thumbnail from client

### ISSUE THREAD

**Issue by Hacksore** [Notifydotme/notifyme-issues#15]
## Expected Behavior
Server to parse the thumbnail from YT API.

## Actual Behavior
Client post's the thumbnail and server users that image.

## Steps to Reproduce the Problem
thumbnail value is send back to the server.
![image](https://user-images.githubusercontent.com/996134/43358234-ec6a105a-9253-11e8-8fb7-4403703d521d.png)

```powershell
Invoke-WebRequest -Uri "https://api-notify-me.herokuapp.com/post/new/" -Method "POST" -Headers @{"Accept"="application/json, text/plain, */*"; "Referer"="https://notifyme-206807.firebaseapp.com/"; "Origin"="https://notifyme-206807.firebaseapp.com"; "User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"; "Authorization"="REDACTED"} -ContentType "application/json;charset=UTF-8" -Body "{`"owner`":50,`"platform`":`"youtube`",`"title`":`"EU LCS Summer (2018) | Week 6 Day 2`",`"link`":`"https://www.youtube.com/watch?v=VXSk3J2SUAI`",`"message`":`"`",`"thumbnail`":`"https://i.imgur.com/oQvctQk.png`",`"datePublished`":`"2018-07-25T18:02:44.000Z`",`"duration`":`"PT0S`",`"topics`":{`"0`":`"gaming`"}}"
```

## Specifications

  - Browser: N/A
  - Operating System: N/A

**Comment by jamiepine** [comment]
we will actually support custom thumbnails so idk if this is actually worth fixing?

**Comment by mercxry** [comment]
No, this is a case where a bug become a feature.
Closed as wontfix.
