### ISSUE TITLE
Open source all notify.me source code

### ISSUE THREAD

**Issue by LemonAndroid** [Notifydotme/notifyme-issues#16]
## Expected Behavior

Cool open source project, where everybody can get involved.

## Actual Behavior
Make sure to include screenshots!

## Steps to Reproduce the Problem

  1. Go to notifydotme github
  2. Hope it's open source
  3. Remember it's not

## Specifications

  - Browser: Chrome
  - Operating System: Ubuntu

![screenshot from 2018-07-29 23-47-35](https://user-images.githubusercontent.com/3209250/43371012-d226d58e-9389-11e8-84e1-f132351f61e0.png)

**Comment by mercxry** [comment]
Not a bug, wontdfix.
