### ISSUE TITLE
Create Account button on login does not work

### ISSUE THREAD

**Issue by TheSilvus** [Notifydotme/notifyme-issues#18]
## Expected Behavior
Clicking the "Create Account" button on the top right of the /login page should open the /create route.

## Actual Behavior
It reload the page and reopens /login

## Steps to Reproduce the Problem

  1. Open /login page (not logged in)
  2. Click "Create Account" on the top right and compare behavior to pressing "Create One Now" below the login form

## Specifications

  - Browser: Firefox
  - Operating System: Windows 10

**Comment by mercxry** [comment]
Fixed
