### ISSUE TITLE
Error on create post

### ISSUE THREAD

**Issue by LemonAndroid** [Notifydotme/notifyme-issues#21]
## Expected Behavior

When I click on Send after pasting an valid YouTube URL for a new post, it must be created.

## Actual Behavior

The post is not created, the modal for creating a post is still there.

## Steps to Reproduce the Problem

  1. Open the modal for creating posts
  2. Paste in any YouTube URL
  3. Click "Send"

## Specifications

  - Browser: Google Chrome Version 68.0.3440.84 (Offizieller Build) (32-Bit)
  - Operating System: Windows 10 Home Version 1803 Build 17134.48

Error message: 

```
{"errorCode":"validation_error","errors":{"duration":["Duration must follow the 'ISO 8601' standard for durations"]}}
```
Erring endpoint:
/post/new

Erring payload:

```
{owner: 126, platform: "youtube", title: "Nightmares on Wax - You Wish",…}
datePublished
:
"2014-12-11T15:00:18.000Z"
duration
:
"PT3M31S"
link
:
"https://www.youtube.com/watch?v=TwDOa-lvizM"
message
:
""
owner
:
126
platform
:
"youtube"
thumbnail
:
"https://i.ytimg.com/vi/TwDOa-lvizM/mqdefault.jpg"
title
:
"Nightmares on Wax - You Wish"
topics
:
{0: "fortnite"}
```

# Screenshot
![image](https://user-images.githubusercontent.com/3209250/43948945-8134f8c0-9c8c-11e8-8405-ec26579da5b6.png)

**Comment by Jackdouglas99** [comment]
This is already fixed
