### ISSUE TITLE
HTTPs insecure

### ISSUE THREAD

**Issue by iilukas** [Notifydotme/notifyme-issues#24]
## Expected Behavior
HTTPS to be enabled

## Actual Behavior
https://plik.root.gg/file/whtuV9t6VGuBQe9A/q61xJFVDmWhHGht4/chrome_2018-08-16_18-31-42.png
https://plik.root.gg/file/Q8SUJkZX2MBVctHl/HlgiA08aJPU5dyVE/chrome_2018-08-16_18-33-09.png

## Steps to Reproduce the Problem

  1. Login to notify.gg
  2. Check the inspect element console.

## Specifications

  - Browser: Chrome
  - Operating System: Windows 10 Home Edition

**Comment by mercxry** [comment]
The Alpha site doesn't have security best practices for the architecture, when we will go off development the platform will have this security problem fixed
