### ISSUE TITLE
White Theme / Dark Theme mixed?

### ISSUE THREAD

**Issue by iamluca** [Notifydotme/notifyme-issues#26]
## Expected Behavior

White Theme to be everything when on White Theme

## Actual Behavior
Make sure to include screenshots!
https://plik.root.gg/file/yz23XEDSHQBRHM9w/fHcTP1X6jEAiG6eH/chrome_2018-09-01_12-24-43.png

## Steps to Reproduce the Problem

  1. Switch from Dark Theme to White Theme and go to a channel

## Specifications

  - Browser: Chrome Latest
  - Operating System: Windows 10 x64

**Comment by Jackdouglas99** [comment]
Also not finished

**Comment by iamluca** [comment]
This seems to be fixed.
