### ISSUE TITLE
Tabs are boldish and look werid

### ISSUE THREAD

**Issue by iamluca** [Notifydotme/notifyme-issues#27]
## Expected Behavior
Tabs to be normal

## Actual Behavior
Make sure to include screenshots!
https://plik.root.gg/file/xopeOHMBykXmr4Lf/JfjzCMhwCbdXGjkW/chrome_2018-09-01_12-26-10.png

## Steps to Reproduce the Problem

  1. Go to Dark theme and go to a channel with videos.

## Specifications

  - Browser: Chrome
  - Operating System: Windows 10 x64

**Comment by Jackdouglas99** [comment]
Not a bug its not finished
