### ISSUE TITLE
Previously subscribed channel shows in Getting Notified column in sub manager after unsub

### ISSUE THREAD

**Issue by LemonAndroid** [Notifydotme/notifyme-issues#28]
## Expected Behavior
Unsubbed channel must not show in Getting Notified or other columns for subbed channels in sub manager.

## Actual Behavior
https://gyazo.com/7e4ea389426c1a4724c949eaee97c9e8

## Steps to Reproduce the Problem

  1. Sub to a channel
  2. Unsub to channel form 1
  3. Go to Sub manager and find it in Getting notified column

## Specifications

  - Browser: Version 68.0.3440.106 (Offizieller Build) (64-Bit)
  - Operating System: Windows 10 Version 1803
 https://gyazo.com/a659e6f8a12585c3254e63825d7bf98e

**Comment by Jackdouglas99** [comment]
This is fixed
